{% set version = "2.1.0" %}

package:
  name: astra-toolbox
  version: {{ version }}

source:
  url: https://github.com/astra-toolbox/astra-toolbox/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7768863a2756887e54829725e8fe95a371c7cb0cdfa5392b2e11cfc290f54dc3

build:
  number: 0
  # libastra is only available for these platforms presently:
  skip: true  # [not (linux64 or win64)]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.13
    # libastra includes boost in its public headers
    - boost-cpp
    - libastra =={{ version.split('.')[:2]|join('.') }}
    - numpy
    - python
    - setuptools
    - scipy
    - six
  run:
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - six

test:
  imports:
    - astra
  requires:
    # To avoid large downloads just for testing after build phase
    - nomkl  # [not win]
    # import scipy.sparse.linalg fails with mkl-2017.0.4 on Windows
    - mkl !=2017.0.4  # [win]
    # scipy 1.1.0 packages are broken with python 2.7 and some numpy versions
    - scipy !=1.1.0  # [py==27]
  commands:
    - python -c "import astra; astra.test()"

about:
  home: http://www.astra-toolbox.com
  license: GPL-3.0-only
  license_file:
    - COPYING
    - lib/licenses/rapidxml.txt
  summary: >
    The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.

extra:
  recipe-maintainers:
    - carterbox
