github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
provider:
  linux_ppc64le: default  # succeeded on Travis
  linux_aarch64: azure    # failed mysteriously on Travis
